### ISSUE TITLE
關於 mobile app client 的情境

### ISSUE THREAD

**Issue by mosluce** [andrew0928/MeetUp.ApiTokenDemo#1]
1. mobile app 環境下 ip 常常會變來變去，有其他推薦可以紀錄的資訊嗎？
2. 如果 token 過期想要 refresh 應該要如何做會比較安全呢

**Comment by andrew0928** [comment]
1. ip address 只是個驗證的資訊之一，mobile app 可以考慮用 device unique id.. 
   app 比較少寫，我記得 iOS 後來好像不准 app access device id, 可以自己產生一個 guid 存起來用。一個不夠用的話，也可以多擺幾個資訊一起驗證，有辦法抓到電話號碼也是個不錯的選擇
2. session token 嗎? 通常這種是過期就丟掉, 可以到 auth 重要一次。只要有 public key 都可以解開 token 驗證裡面的內容。比較好的方式是在 app 端自己解開驗證，不用等到送去 server 後才被踢回來..。

**Comment by mosluce** [comment]
大致瞭解～
